Create a database based on a diagram
tjay1760/Vet-Clinic-Database pull request #5
Opened 2023-08-22 12:56 UTC by MesakDuduCoder

# In this pull request me and my partner implemented the following

* We made tables based on a given diagram
* We made tables for many-to-many relationships between medical_histories and treatments tables
* We added foreign keys to the tables

2023-08-22 13:45 UTC, LionRouge1 requested changes
Hi @MesakDuduCoder, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Nice work creating all the tables on the diagram :1st_place_medal: 
- Great job setting up **PRIMARY KEY** for all the table

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 13:45 UTC, LionRouge1 commented on schema_based_on_diagram.sql
- [ ] Nice work creating the table :clap: However it would be nice to also create `indexes` for all the **FOREIGN KEYS**. That will speed up the data retrieval on the tables which will significantly improve the performance of the database.
**E.g.** `CREATE INDEX ON medical_histories (patient_id);`

2023-08-22 13:45 UTC, LionRouge1 commented on schema_based_on_diagram.sql
> +);
- [ ] Kindly note that there is a many-to-many relationship between the `medical_histories` table and the `treatments` table. Therefore we should have a **join table** between the two tables containing the `medical_history_id` as **FOREIGN KEYS** and `treatments` as **FOREIGN KEYS** referencing the `medical_histories(id)` and the `treatments(id)` respectively.

2023-08-23 05:42 UTC, TadesseDev approved these changes
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![AmazingCreepyFrogmouth-max-1mb](https://user-images.githubusercontent.com/69077061/255314805-13569584-0c0e-4b38-a0bd-94d901ba8a1e.gif)




## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 09:10 UTC, merged